In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6,7,8,9,0])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [5]:
print(a.sum())

45


In [6]:
print(a.max())

9


In [7]:
print(a.min())

0


In [8]:
print(a.ndim)

1


In [9]:
print(a.size)

10


In [14]:
print(a[0:,5])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [16]:
print(a.dtype)

int32


In [17]:
print(a.shape)

(10,)


In [18]:
d=np.array([(1,2,3,4,5),(6,7,8,9,1)])
print(d)

[[1 2 3 4 5]
 [6 7 8 9 1]]


In [19]:
print(d.size)

10


In [22]:
print(d.shape)

(2, 5)


In [23]:
print(d.reshape(5,2))

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 1]]


In [25]:
print(np.sqrt(d))

[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         1.        ]]


In [28]:
t=np.array([(11,22,33),(44,55,66)])
y=np.array([(9,8,7),(6,5,4)])
print(t+y)

[[20 30 40]
 [50 60 70]]


In [29]:
print(t-y)

[[ 2 14 26]
 [38 50 62]]


In [30]:
print(t*y)

[[ 99 176 231]
 [264 275 264]]


In [31]:
print(t/y)

[[ 1.22222222  2.75        4.71428571]
 [ 7.33333333 11.         16.5       ]]


In [34]:
print(np.vstack((t,y)))

[[11 22 33]
 [44 55 66]
 [ 9  8  7]
 [ 6  5  4]]


In [35]:
print(np.hstack((t,y)))

[[11 22 33  9  8  7]
 [44 55 66  6  5  4]]


In [37]:
print(t.ravel())

[11 22 33 44 55 66]


In [38]:
print(y.ravel())

[9 8 7 6 5 4]


In [39]:
h=np.array([[1,2,3,4,5],[6,7,8,9,0]])
h

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [42]:
p=np.zeros((5,5))
p

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
g=np.random.random((5,5))
g

array([[0.99953272, 0.69887924, 0.16965805, 0.74873735, 0.78022028],
       [0.89818559, 0.20354002, 0.39775927, 0.4154244 , 0.98812527],
       [0.46581669, 0.93278365, 0.64639211, 0.6625077 , 0.56067702],
       [0.97647647, 0.14069753, 0.72748214, 0.55577452, 0.498543  ],
       [0.30018335, 0.94996793, 0.81089632, 0.46268341, 0.70663746]])

In [46]:
f=np.arange(0,50,4)
f

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [47]:
e=np.array([(1,2,3,4,5,6,7),(7,6,5,4,3,2,1)])
h=e.flatten()
h

array([1, 2, 3, 4, 5, 6, 7, 7, 6, 5, 4, 3, 2, 1])